theme: jekyll-theme-minimal
title: Liam O'Connell
description: Native New Yorker interested in urban history & transportation policy. Progressive. Studying Social and Political History & Architecture at Carnegie Mellon. Opinions mine. My pronouns are he/him.
